negocio_aleatorio = input("Digite algo:    ")

print("tipo: ", type(negocio_aleatorio))
print("É alfanumerico?  ", negocio_aleatorio.isalnum())
print("Todas as letras sao maiusculas?  ", negocio_aleatorio.isupper())
print("Somente letras?  ", negocio_aleatorio.isalpha())
print("Pertence ao codigo ascii?  ", negocio_aleatorio.isascii())
print("É numero decimal?  ", negocio_aleatorio.isdecimal())
print("É numerico?  ", negocio_aleatorio.isnumeric())
print("É palavra reservada?  ", negocio_aleatorio.isidentifier())
print("É printavel?  ", negocio_aleatorio.isprintable())
print("É um titulo(?)?  ", negocio_aleatorio.istitle())
print("É todas as letras sao minusculas?  ", negocio_aleatorio.islower())
print("É um espaco em branco?  ", negocio_aleatorio.isspace())
